-- Sample Indian baby names for database testing.
-- Load after database/schema.sql has created the baby_names table.

INSERT INTO baby_names (
  name,
  slug,
  gender,
  origin,
  meaning,
  starting_letter,
  numerology_number,
  style_label,
  is_premium,
  school,
  religion,
  name_length,
  pronunciation_score,
  usability_score,
  rarity_score
) VALUES
('Aarav', 'aarav', 'BOY', 'Sanskrit', 'Peaceful and wise', 'A', 6, 'Modern', FALSE, 'Vedic', 'Hindu', 5, 94.00, 96.00, 28.00),
('Ayaan', 'ayaan', 'BOY', 'Sanskrit', 'Gift of God and bright path', 'A', 7, 'Modern', FALSE, 'Contemporary', 'Hindu', 5, 92.00, 95.00, 32.00),
('Vihaan', 'vihaan', 'BOY', 'Sanskrit', 'Dawn or beginning of a new era', 'V', 9, 'Modern Sanskrit', FALSE, 'Vedic', 'Hindu', 6, 90.00, 92.00, 36.00),
('Reyansh', 'reyansh', 'BOY', 'Sanskrit', 'Ray of light', 'R', 1, 'Modern', FALSE, 'Contemporary', 'Hindu', 7, 88.00, 91.00, 35.00),
('Ivaan', 'ivaan', 'BOY', 'Sanskrit', 'Royal and gracious gift', 'I', 2, 'Modern', TRUE, 'Contemporary', 'Hindu', 5, 91.00, 90.00, 52.00),
('Arjun', 'arjun', 'BOY', 'Sanskrit', 'Bright, pure, and courageous', 'A', 1, 'Classic', FALSE, 'Epic', 'Hindu', 5, 96.00, 97.00, 20.00),
('Kabir', 'kabir', 'BOY', 'Arabic', 'Great and powerful', 'K', 5, 'Spiritual', FALSE, 'Bhakti', 'Indian', 5, 95.00, 96.00, 26.00),
('Advait', 'advait', 'BOY', 'Sanskrit', 'Unique and non-dual', 'A', 3, 'Sanskrit-inspired', TRUE, 'Vedanta', 'Hindu', 6, 86.00, 88.00, 61.00),
('Atharv', 'atharv', 'BOY', 'Sanskrit', 'Wise and learned in sacred knowledge', 'A', 7, 'Vedic', FALSE, 'Vedic', 'Hindu', 6, 87.00, 88.00, 40.00),
('Dhruv', 'dhruv', 'BOY', 'Sanskrit', 'Steady like the pole star', 'D', 1, 'Classic', FALSE, 'Vedic', 'Hindu', 5, 91.00, 93.00, 30.00),
('Eshan', 'eshan', 'BOY', 'Sanskrit', 'Lord Shiva and the northeast direction', 'E', 2, 'Spiritual', FALSE, 'Vedic', 'Hindu', 5, 92.00, 93.00, 39.00),
('Ishaan', 'ishaan', 'BOY', 'Sanskrit', 'Sun, ruler, and Lord Shiva', 'I', 7, 'Spiritual', FALSE, 'Vedic', 'Hindu', 6, 91.00, 94.00, 31.00),
('Krishiv', 'krishiv', 'BOY', 'Sanskrit', 'A name inspired by Krishna and Shiva', 'K', 5, 'Modern Sanskrit', TRUE, 'Devotional', 'Hindu', 7, 82.00, 85.00, 72.00),
('Laksh', 'laksh', 'BOY', 'Sanskrit', 'Aim, target, or goal', 'L', 6, 'Minimal', FALSE, 'Contemporary', 'Hindu', 5, 91.00, 92.00, 45.00),
('Neel', 'neel', 'BOY', 'Sanskrit', 'Blue, sapphire, or sky-colored', 'N', 9, 'Minimal', FALSE, 'Nature', 'Hindu', 4, 96.00, 96.00, 34.00),
('Rudra', 'rudra', 'BOY', 'Sanskrit', 'A powerful form of Lord Shiva', 'R', 8, 'Mythic', FALSE, 'Vedic', 'Hindu', 5, 91.00, 89.00, 38.00),
('Shaurya', 'shaurya', 'BOY', 'Sanskrit', 'Bravery and valor', 'S', 5, 'Royal', FALSE, 'Vedic', 'Hindu', 7, 86.00, 88.00, 46.00),
('Vivaan', 'vivaan', 'BOY', 'Sanskrit', 'Full of life', 'V', 7, 'Modern', FALSE, 'Contemporary', 'Hindu', 6, 92.00, 95.00, 29.00),
('Zayan', 'zayan', 'BOY', 'Arabic', 'Graceful and beautiful', 'Z', 4, 'Modern', TRUE, 'Contemporary', 'Indian', 5, 93.00, 91.00, 56.00),
('Aarush', 'aarush', 'BOY', 'Sanskrit', 'First ray of the sun', 'A', 5, 'Nature', FALSE, 'Vedic', 'Hindu', 6, 90.00, 91.00, 37.00),
('Anay', 'anay', 'BOY', 'Sanskrit', 'Without a superior', 'A', 5, 'Minimal', TRUE, 'Vedanta', 'Hindu', 4, 94.00, 92.00, 64.00),
('Devansh', 'devansh', 'BOY', 'Sanskrit', 'Part of the divine', 'D', 1, 'Devotional', FALSE, 'Vedic', 'Hindu', 7, 88.00, 90.00, 42.00),
('Hriday', 'hriday', 'BOY', 'Sanskrit', 'Heart', 'H', 2, 'Sanskrit-inspired', TRUE, 'Vedic', 'Hindu', 6, 83.00, 84.00, 70.00),
('Kiaan', 'kiaan', 'BOY', 'Sanskrit', 'Grace of God and ancient king', 'K', 9, 'Modern', TRUE, 'Contemporary', 'Hindu', 5, 91.00, 90.00, 58.00),
('Nirvaan', 'nirvaan', 'BOY', 'Sanskrit', 'Liberation and peaceful bliss', 'N', 7, 'Spiritual', TRUE, 'Vedanta', 'Hindu', 7, 85.00, 86.00, 68.00),
('Ojas', 'ojas', 'BOY', 'Sanskrit', 'Vital energy and strength', 'O', 9, 'Sanskrit-inspired', TRUE, 'Ayurveda', 'Hindu', 4, 92.00, 88.00, 67.00),
('Prayan', 'prayan', 'BOY', 'Sanskrit', 'Journey or progress', 'P', 3, 'Modern Sanskrit', TRUE, 'Contemporary', 'Hindu', 6, 86.00, 84.00, 78.00),
('Ritvik', 'ritvik', 'BOY', 'Sanskrit', 'Priest or one who performs sacred rites', 'R', 8, 'Vedic', FALSE, 'Vedic', 'Hindu', 6, 88.00, 86.00, 49.00),
('Samarth', 'samarth', 'BOY', 'Sanskrit', 'Capable and powerful', 'S', 8, 'Classic', FALSE, 'Vedic', 'Hindu', 7, 88.00, 90.00, 43.00),
('Tanish', 'tanish', 'BOY', 'Sanskrit', 'Ambition or jewel', 'T', 8, 'Modern', FALSE, 'Contemporary', 'Hindu', 6, 89.00, 91.00, 44.00),
('Vedant', 'vedant', 'BOY', 'Sanskrit', 'Ultimate wisdom of the Vedas', 'V', 3, 'Vedic', FALSE, 'Vedanta', 'Hindu', 6, 90.00, 91.00, 41.00),
('Yuvaan', 'yuvaan', 'BOY', 'Sanskrit', 'Youthful and energetic', 'Y', 3, 'Modern', TRUE, 'Contemporary', 'Hindu', 6, 89.00, 88.00, 62.00),
('Aariv', 'aariv', 'BOY', 'Sanskrit', 'King of wisdom and peaceful strength', 'A', 6, 'Premium Modern', TRUE, 'Contemporary', 'Hindu', 5, 90.00, 88.00, 73.00),
('Samar', 'samar', 'BOY', 'Sanskrit', 'Battle, evening conversation, or reward', 'S', 7, 'Minimal', FALSE, 'Contemporary', 'Indian', 5, 94.00, 95.00, 33.00),
('Ahan', 'ahan', 'BOY', 'Sanskrit', 'Dawn and first ray of light', 'A', 6, 'Minimal', FALSE, 'Nature', 'Hindu', 4, 95.00, 94.00, 51.00),
('Riaan', 'riaan', 'BOY', 'Sanskrit', 'Little king and graceful one', 'R', 7, 'Modern', TRUE, 'Contemporary', 'Indian', 5, 92.00, 91.00, 57.00),
('Veer', 'veer', 'BOY', 'Sanskrit', 'Brave and heroic', 'V', 5, 'Royal', FALSE, 'Classic', 'Indian', 4, 97.00, 96.00, 25.00),
('Darsh', 'darsh', 'BOY', 'Sanskrit', 'Sight, vision, or handsome', 'D', 5, 'Sanskrit-inspired', FALSE, 'Vedic', 'Hindu', 5, 91.00, 90.00, 47.00),
('Kavish', 'kavish', 'BOY', 'Sanskrit', 'Lord of poets', 'K', 7, 'Artistic', TRUE, 'Literary', 'Hindu', 6, 87.00, 86.00, 69.00),
('Sivaan', 'sivaan', 'BOY', 'Sanskrit', 'A graceful name inspired by Shiva', 'S', 3, 'Devotional', TRUE, 'Devotional', 'Hindu', 6, 88.00, 85.00, 76.00),
('Aadhya', 'aadhya', 'GIRL', 'Sanskrit', 'First power and primordial energy', 'A', 4, 'Sanskrit-inspired', FALSE, 'Shakti', 'Hindu', 6, 87.00, 90.00, 38.00),
('Anaya', 'anaya', 'GIRL', 'Sanskrit', 'Caring, protected, and graceful', 'A', 6, 'Modern', FALSE, 'Contemporary', 'Hindu', 5, 94.00, 96.00, 30.00),
('Aarohi', 'aarohi', 'GIRL', 'Sanskrit', 'Ascending musical note', 'A', 7, 'Artistic', FALSE, 'Music', 'Hindu', 6, 90.00, 92.00, 42.00),
('Ira', 'ira', 'GIRL', 'Sanskrit', 'Earth, speech, and goddess Saraswati', 'I', 1, 'Minimal', FALSE, 'Vedic', 'Hindu', 3, 98.00, 97.00, 35.00),
('Kiara', 'kiara', 'GIRL', 'Sanskrit', 'Bright, clear, and graceful', 'K', 4, 'Modern', FALSE, 'Contemporary', 'Indian', 5, 94.00, 95.00, 33.00),
('Myra', 'myra', 'GIRL', 'Sanskrit', 'Beloved and admirable', 'M', 3, 'Modern', FALSE, 'Contemporary', 'Indian', 4, 96.00, 96.00, 28.00),
('Saanvi', 'saanvi', 'GIRL', 'Sanskrit', 'Goddess Lakshmi and knowledge', 'S', 3, 'Devotional', FALSE, 'Vedic', 'Hindu', 6, 89.00, 93.00, 27.00),
('Anika', 'anika', 'GIRL', 'Sanskrit', 'Graceful and fearless', 'A', 9, 'Modern Sanskrit', FALSE, 'Shakti', 'Hindu', 5, 94.00, 96.00, 31.00),
('Avni', 'avni', 'GIRL', 'Sanskrit', 'Earth', 'A', 1, 'Nature', FALSE, 'Vedic', 'Hindu', 4, 96.00, 96.00, 37.00),
('Diya', 'diya', 'GIRL', 'Sanskrit', 'Lamp and light', 'D', 3, 'Minimal', FALSE, 'Nature', 'Indian', 4, 97.00, 98.00, 24.00),
('Ishani', 'ishani', 'GIRL', 'Sanskrit', 'Goddess Durga and divine power', 'I', 6, 'Devotional', FALSE, 'Shakti', 'Hindu', 6, 90.00, 92.00, 41.00),
('Kashvi', 'kashvi', 'GIRL', 'Sanskrit', 'Shining and radiant', 'K', 7, 'Modern Sanskrit', TRUE, 'Contemporary', 'Hindu', 6, 88.00, 88.00, 63.00),
('Mishka', 'mishka', 'GIRL', 'Sanskrit', 'Gift of love', 'M', 8, 'Modern', TRUE, 'Contemporary', 'Indian', 6, 90.00, 90.00, 59.00),
('Navya', 'navya', 'GIRL', 'Sanskrit', 'New, young, and praiseworthy', 'N', 9, 'Modern', FALSE, 'Contemporary', 'Hindu', 5, 95.00, 96.00, 29.00),
('Prisha', 'prisha', 'GIRL', 'Sanskrit', 'Beloved and God-gifted', 'P', 8, 'Modern', FALSE, 'Contemporary', 'Hindu', 6, 90.00, 93.00, 34.00),
('Riva', 'riva', 'GIRL', 'Sanskrit', 'River bank and graceful flow', 'R', 5, 'Nature', TRUE, 'Nature', 'Hindu', 4, 96.00, 94.00, 60.00),
('Siya', 'siya', 'GIRL', 'Sanskrit', 'Goddess Sita', 'S', 9, 'Devotional', FALSE, 'Epic', 'Hindu', 4, 97.00, 98.00, 25.00),
('Tara', 'tara', 'GIRL', 'Sanskrit', 'Star', 'T', 4, 'Nature', FALSE, 'Vedic', 'Indian', 4, 98.00, 97.00, 26.00),
('Vanya', 'vanya', 'GIRL', 'Sanskrit', 'Forest and gracious gift of God', 'V', 9, 'Nature', TRUE, 'Nature', 'Hindu', 5, 94.00, 93.00, 55.00),
('Zara', 'zara', 'GIRL', 'Arabic', 'Radiance and blooming flower', 'Z', 1, 'Modern', FALSE, 'Contemporary', 'Indian', 4, 97.00, 96.00, 36.00),
('Aarini', 'aarini', 'GIRL', 'Sanskrit', 'Adventurous and radiant', 'A', 7, 'Premium Modern', TRUE, 'Contemporary', 'Hindu', 6, 89.00, 87.00, 74.00),
('Bhavya', 'bhavya', 'GIRL', 'Sanskrit', 'Grand, splendid, and graceful', 'B', 5, 'Classic', FALSE, 'Vedic', 'Hindu', 6, 88.00, 90.00, 44.00),
('Charvi', 'charvi', 'GIRL', 'Sanskrit', 'Beautiful and lovely', 'C', 7, 'Sanskrit-inspired', FALSE, 'Vedic', 'Hindu', 6, 89.00, 89.00, 48.00),
('Eshika', 'eshika', 'GIRL', 'Sanskrit', 'Arrow, dart, and divine aim', 'E', 8, 'Modern Sanskrit', TRUE, 'Vedic', 'Hindu', 6, 88.00, 87.00, 65.00),
('Inaaya', 'inaaya', 'GIRL', 'Arabic', 'Care, protection, and kindness', 'I', 6, 'Modern', FALSE, 'Contemporary', 'Indian', 6, 91.00, 94.00, 39.00),
('Jivika', 'jivika', 'GIRL', 'Sanskrit', 'Source of life', 'J', 8, 'Sanskrit-inspired', TRUE, 'Vedic', 'Hindu', 6, 87.00, 86.00, 71.00),
('Kiyana', 'kiyana', 'GIRL', 'Sanskrit', 'Divine and graceful', 'K', 7, 'Premium Modern', TRUE, 'Contemporary', 'Indian', 6, 90.00, 88.00, 73.00),
('Lavanya', 'lavanya', 'GIRL', 'Sanskrit', 'Grace and beauty', 'L', 5, 'Classic', FALSE, 'Vedic', 'Hindu', 7, 89.00, 90.00, 43.00),
('Mahika', 'mahika', 'GIRL', 'Sanskrit', 'Earth and dew drops', 'M', 8, 'Nature', TRUE, 'Nature', 'Hindu', 6, 88.00, 87.00, 66.00),
('Naira', 'naira', 'GIRL', 'Sanskrit', 'Radiant and shining', 'N', 7, 'Modern', TRUE, 'Contemporary', 'Indian', 5, 94.00, 93.00, 57.00),
('Oviya', 'oviya', 'GIRL', 'Tamil', 'Beautiful artist or painting', 'O', 9, 'Artistic', TRUE, 'Literary', 'Indian', 5, 91.00, 89.00, 69.00),
('Parina', 'parina', 'GIRL', 'Sanskrit', 'Fairy-like and complete', 'P', 5, 'Modern Sanskrit', TRUE, 'Contemporary', 'Hindu', 6, 89.00, 87.00, 72.00),
('Ruhani', 'ruhani', 'GIRL', 'Sanskrit', 'Spiritual and soulful', 'R', 8, 'Spiritual', TRUE, 'Contemporary', 'Indian', 6, 90.00, 89.00, 64.00),
('Samaira', 'samaira', 'GIRL', 'Sanskrit', 'Enchanting and protected by God', 'S', 8, 'Modern', FALSE, 'Contemporary', 'Indian', 7, 88.00, 92.00, 40.00),
('Tanvi', 'tanvi', 'GIRL', 'Sanskrit', 'Delicate, slender, and beautiful', 'T', 3, 'Classic', FALSE, 'Vedic', 'Hindu', 5, 94.00, 95.00, 32.00),
('Urvi', 'urvi', 'GIRL', 'Sanskrit', 'Earth and vastness', 'U', 7, 'Nature', TRUE, 'Vedic', 'Hindu', 4, 94.00, 90.00, 62.00),
('Vedika', 'vedika', 'GIRL', 'Sanskrit', 'Altar, consciousness, and sacred knowledge', 'V', 7, 'Vedic', FALSE, 'Vedic', 'Hindu', 6, 90.00, 91.00, 45.00),
('Yashvi', 'yashvi', 'GIRL', 'Sanskrit', 'Fame and glory', 'Y', 5, 'Modern Sanskrit', TRUE, 'Contemporary', 'Hindu', 6, 88.00, 87.00, 67.00),
('Ziva', 'ziva', 'GIRL', 'Sanskrit', 'Radiance, brilliance, and life', 'Z', 4, 'Modern', TRUE, 'Contemporary', 'Indian', 4, 96.00, 94.00, 58.00),
('Aashi', 'aashi', 'GIRL', 'Sanskrit', 'Smile, joy, and blessing', 'A', 2, 'Modern', FALSE, 'Contemporary', 'Hindu', 5, 94.00, 95.00, 41.00),
('Arin', 'arin', 'UNISEX', 'Sanskrit', 'Mountain strength and peaceful energy', 'A', 6, 'Modern Sanskrit', TRUE, 'Nature', 'Indian', 4, 94.00, 92.00, 70.00),
('Aadi', 'aadi', 'UNISEX', 'Sanskrit', 'Beginning and first', 'A', 6, 'Minimal', FALSE, 'Vedic', 'Hindu', 4, 96.00, 96.00, 34.00),
('Akira', 'akira', 'UNISEX', 'Sanskrit', 'Graceful strength and bright light', 'A', 4, 'Modern', TRUE, 'Contemporary', 'Indian', 5, 94.00, 92.00, 63.00),
('Arya', 'arya', 'UNISEX', 'Sanskrit', 'Noble and honorable', 'A', 9, 'Classic', FALSE, 'Vedic', 'Indian', 4, 97.00, 98.00, 22.00),
('Avyan', 'avyan', 'UNISEX', 'Sanskrit', 'Eloquent and clear', 'A', 9, 'Modern Sanskrit', TRUE, 'Contemporary', 'Hindu', 5, 91.00, 89.00, 71.00),
('Daksh', 'daksh', 'UNISEX', 'Sanskrit', 'Skilled and capable', 'D', 7, 'Sanskrit-inspired', FALSE, 'Vedic', 'Hindu', 5, 91.00, 90.00, 46.00),
('Divit', 'divit', 'UNISEX', 'Sanskrit', 'Immortal and divine', 'D', 1, 'Modern Sanskrit', TRUE, 'Vedic', 'Hindu', 5, 91.00, 89.00, 62.00),
('Eka', 'eka', 'UNISEX', 'Sanskrit', 'One and unique', 'E', 8, 'Minimal', TRUE, 'Vedanta', 'Hindu', 3, 97.00, 94.00, 74.00),
('Harit', 'harit', 'UNISEX', 'Sanskrit', 'Green and full of life', 'H', 2, 'Nature', FALSE, 'Nature', 'Hindu', 5, 91.00, 89.00, 52.00),
('Ina', 'ina', 'UNISEX', 'Sanskrit', 'Strong, luminous, and motherly', 'I', 6, 'Minimal', TRUE, 'Contemporary', 'Indian', 3, 98.00, 95.00, 76.00),
('Jiya', 'jiya', 'UNISEX', 'Sanskrit', 'Heart and life', 'J', 9, 'Minimal', FALSE, 'Contemporary', 'Indian', 4, 96.00, 96.00, 38.00),
('Kairav', 'kairav', 'UNISEX', 'Sanskrit', 'White lotus', 'K', 8, 'Nature', TRUE, 'Nature', 'Hindu', 6, 89.00, 88.00, 66.00),
('Kivan', 'kivan', 'UNISEX', 'Sanskrit', 'Ray of wisdom and graceful strength', 'K', 9, 'Premium Modern', TRUE, 'Contemporary', 'Indian', 5, 91.00, 89.00, 69.00),
('Moksh', 'moksh', 'UNISEX', 'Sanskrit', 'Liberation and spiritual freedom', 'M', 3, 'Spiritual', FALSE, 'Vedanta', 'Hindu', 5, 91.00, 90.00, 47.00),
('Niral', 'niral', 'UNISEX', 'Sanskrit', 'Unique and calm', 'N', 9, 'Sanskrit-inspired', TRUE, 'Contemporary', 'Indian', 5, 92.00, 89.00, 72.00),
('Oorja', 'oorja', 'UNISEX', 'Sanskrit', 'Energy and vitality', 'O', 5, 'Nature', TRUE, 'Ayurveda', 'Hindu', 5, 86.00, 84.00, 78.00),
('Pranit', 'pranit', 'UNISEX', 'Sanskrit', 'Leader and guided one', 'P', 6, 'Sanskrit-inspired', TRUE, 'Vedic', 'Hindu', 6, 88.00, 87.00, 64.00),
('Reva', 'reva', 'UNISEX', 'Sanskrit', 'Sacred river and graceful movement', 'R', 1, 'Nature', FALSE, 'Vedic', 'Hindu', 4, 96.00, 95.00, 44.00),
('Saarin', 'saarin', 'UNISEX', 'Sanskrit', 'Essence and meaningful one', 'S', 8, 'Premium Modern', TRUE, 'Vedanta', 'Hindu', 6, 89.00, 86.00, 80.00),
('Tavish', 'tavish', 'UNISEX', 'Sanskrit', 'Heavenly and courageous', 'T', 9, 'Royal', TRUE, 'Vedic', 'Hindu', 6, 88.00, 87.00, 68.00);
